package com.bookmyshow.app.models;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public abstract class Exposed extends Auditable {
    private String uuid; // autogenerated at the time of object creation
    // we will have to place an index on this
}
